# -*- coding: utf-8 -*-
"""task11

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UtdCRcWxXXvyzofPTNgzVDsxe0D7mgC-
"""

import pandas as pd
import numpy as np

from pyclustertend import vat

data=pd.read_csv("/content/wine-clustering.csv")

data

data = pd.get_dummies(data,columns = ['Alcohol','Malic_Acid','Ash','Ash_Alcanity','Magnesium','Total_Phenols','Flavanoids','Nonflavanoid_Phenols','Proanthocyanins','Color_Intensity','Hue','OD280','Proline'])

data_array = data.values
data_array

vat(data_array)

from pyclustertend import ivat

ivat(data_array)